import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  allowedDevOrigins: [
    '127.0.0.1',
  ],
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: '*.mlstatic.com', pathname: '/**' },
      { protocol: 'https', hostname: 'i.imgur.com', pathname: '/**' },
      { protocol: 'https', hostname: 'images.unsplash.com', pathname: '/**' },
      { protocol: 'https', hostname: '*.vteximg.com.br', pathname: '/**' },
      { protocol: 'https', hostname: 'mexx-img-2019.s3.amazonaws.com', pathname: '/**' },
      { protocol: 'https', hostname: 'imagenes.compragamer.com', pathname: '/**' },
      { protocol: 'https', hostname: 'www.venex.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'www.fullh4rd.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'compugarden.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: '*.compugarden.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'gamingcity.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'www.gamingcity.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'logg.api.cygnus.market', pathname: '/**' },
      { protocol: 'https', hostname: 'katech.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'dinobyte.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'maxtecno.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'thegamershop.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'hardcorecomputacion.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'goldentechstore.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'www.armytech.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'beings.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'rockethard.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'hypergaming.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'hftecnologia.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'clickgaming.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'megasoftargentina.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'noxiestore.com', pathname: '/**' },
      { protocol: 'https', hostname: 'nb.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'invidcomputers.com', pathname: '/**' },
      { protocol: 'https', hostname: 'portalstore.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: '*.acdn-us.mitiendanube.com', pathname: '/**' },
      { protocol: 'https', hostname: 'www.acuarioinsumos.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'www.gamerspoint.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'liontech.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'www.scphardstore.com', pathname: '/**' },
      { protocol: 'https', hostname: 'spacegamer.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'vrx.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'wiztech.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'www.xt-pc.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'cdn.qloud.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'statics.qloud.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'statics.qloud.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'statics2.qloud.com.ar', pathname: '/**' },
      { protocol: 'https', hostname: 'app.contabilium.com', pathname: '/**' },
    ],
  },
};

export default nextConfig;
