import { readFile } from 'node:fs/promises';
import { getServerSupabaseServiceClient } from '../../src/lib/server/supabase-server';
import { parseCatalogInterest } from '../../src/lib/catalog/analytics-interest';
import { importCatalogInterest } from '../../src/lib/catalog/import-interest';
const [path] = process.argv.slice(2);
if (!path) throw new Error('REFRESH_INTEREST_FILE_REQUIRED');
const rows = parseCatalogInterest(JSON.parse(await readFile(path,'utf8')));
const client = getServerSupabaseServiceClient();
if (!client) throw new Error('REFRESH_DATABASE_UNAVAILABLE');
process.stdout.write(JSON.stringify(await importCatalogInterest(client, rows))+'\n');
